EXTRA_CONFIG= ${OPENBUS_HOME}/config

PROJNAME = lce
LIBNAME = ${PROJNAME}

TARGETROOT= ${OPENBUS_HOME}/libpath

OPENSSL_INC= ${OPENSSL_HOME}/include
OPENSSL_LIB= ${OPENSSL_HOME}
OPENSSL_LIBS = crypto

INCLUDES= ../include ${OPENSSL_INC}
LDIR= ${OPENSSL_LIB}
LIBS= ${OPENSSL_LIBS} dl
SRC= lce.c lce_x509.c lce_key.c lce_cipher.c

USE_LUA51=YES
USE_STATIC=YES
