#ifndef SS_IDL
#define SS_IDL

#include "scs.idl"
#include "core.idl"
#include "access_control_service.idl"

module OpenBus {

module SS {

typedef Identifier SessionIdentifier;

struct Session {
    SessionIdentifier identifier;
};

interface SessionService {
    Session createSession(in AS::Credential credential);
    Session getSession(in AS::Credential credential);
    boolean removeSession(in AS::Credential credential);
};

interface SessionServiceComponent : SCS::IComponent{
};

};

};

#endif
