#ifndef RS_IDL
#define RS_IDL

#include "scs.idl"
#include "core.idl"
#include "access_control_service.idl"

module OpenBus {

module RS {

struct ServiceOffer {
    string description;
    string type;
    SCS::IMetaInterface metaInterface;
};

struct Criterion {
    string name;
    string value;
};
typedef sequence<Criterion> Criteria;

typedef Identifier RegistryIdentifier;

interface RegistryService {
    RegistryIdentifier register(in AS::Credential credential, in ServiceOffer serviceOffer);
    void unregister(in RegistryIdentifier identifier);
    void refresh(in RegistryIdentifier identifier, in ServiceOffer serviceOffer);
    SCS::IComponent find (in Criteria criteria, in string type);
};

interface RegistryServiceComponent : SCS::IComponent {
};

};

};

#endif
