PROJNAME= lpw
LIBNAME= ${PROJNAME}

OPENBUSINC= ${OPENBUS_HOME}/incpath
OPENBUSLIB= ${OPENBUS_HOME}/libpath/${TEC_UNAME}

LDIR= ${OPENBUSLIB}

SRC= lpw.c

USE_LUA51= YES
NO_LUALINK= YES
USE_NODEPEND=YES