#!/bin/ksh

if [[ $1 = "genfiles" ]] ; then
  lua runtestsBig.lua
else
  if [[ $1 = "scp" ]] ; then
#    time scp d3:/tmp/10Gb /tmp/10GbRCVED
    time scp d3:/tmp/20Gb /tmp/20GbRCVED
  else
    runnerBig
  fi
fi

#if [[ $1 = "rmfiles" ]] ; then
# rm -f /tmp/NO_PERMISSION /tmp/20b /tmp/100b /tmp/10b /tmp/10Mb /tmp/10MbRCVED /tmp/50Mb /tmp/100Mb
#fi


