#!/bin/ksh

touch /tmp/NO_PERMISSION
chmod -rw /tmp/NO_PERMISSION

if [[ $1 = "genfiles" ]] ; then
  lua runtests.lua
fi

runnerCo

#if [[ $1 = "rmfiles" ]] ; then
# rm -f /tmp/NO_PERMISSION /tmp/20b /tmp/100b /tmp/10b /tmp/10Mb /tmp/10MbRCVED /tmp/50Mb /tmp/100Mb
#fi

