#!/bin/sh

${OPENBUS_HOME}/core/bin/servicelauncher publisher.lua&

pid=$!
#echo "PID: $pid"
trap "kill $pid > /dev/null 2> /dev/null" 0

sleep 3

${OPENBUS_HOME}/core/bin/servicelauncher consumer.lua

