package tecgraf.openbus.demo.data_service.factorys;

import tecgraf.openbus.demo.data_service.valuetypes.FileDataDescriptionImpl;

/**
 * tecgraf/openbus/file_system/FileDataDescriptionDefaultFactory.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * data_service_demo.idl Terça-feira, 21 de Julho de 2009 16h08min02s BRT
 */

public class FileDataDescriptionDefaultFactory implements
  org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value(
    org.omg.CORBA_2_3.portable.InputStream is) {
    return is.read_value(new FileDataDescriptionImpl());
  }
}
